import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { ThemeProviders } from "@/utils/theme-providers";

const OutfitFont = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "MindBot AI: Into The MindVerse!",
  description: "MindBot AI is a state-of-the-art intelligent AI assistant offering advanced features like MindPaint, MindVision, MindSearch and MindThink-A1. Experience seamless integration for creative tasks, image analysis, and information retrieval. Discover the power of AI at your fingertips with MindBot-1.5-Pro.",
  keywords: [
    "AI", "Artificial Intelligence", "MindBot", "intelligent assistant", "AI assistant",
    "MindPaint", "AI art generator", "image creation", "creative AI",
    "MindVision", "image analysis", "object detection", "visual AI",
    "MindSearch", "AI search engine", "intelligent search", "information retrieval",
    "AI tools", "productivity AI", "machine learning", "natural language processing",
    "chatbot", "AI platform", "personal AI", "virtual assistant",
    "next generation AI", "cutting-edge AI", "advanced AI", "smart assistant",
    "ai chatbot", "ai for creativity", "ai for research", "ai for productivity",
    "ai for image processing", "ai for visual tasks", "ai driven search", "ai technology",
    "ai learning", "ai based tools", "innovative ai", "ai power", "digital assistance", "ai driven solutions",
    "Artificial intelligence platform", "AI solutions", "Machine learning applications", "Deep learning",
    "Neural networks", "AI algorithms", "Natural language understanding (NLU)",
    "Natural language generation (NLG)", "AI software", "AI technology",
    "AI tools for business", "AI innovation", "AI advancements", "AI driven applications",
    "AI computing", "AI processing", "AI powered solutions", "AI digital transformation",
    "AI adoption", "AI research", "Advanced AI", "Next generation AI",
    "Cutting edge AI", "Smart technology", "Cognitive computing", "Data science tools",
    "Predictive analytics", "AI ethics", "AI and society", "AI future trends",
    "AI for everyone", "Ethical AI", "Responsible AI", "Human-centered AI",
    "AI democratization", "AI in everyday life", "AI automation", "AI for efficiency",
    "AI integration", "AI development", "AI engineering", "AI implementation",
    "AI infrastructure", "Cloud AI", "Edge AI", "AI on device", "AI in the cloud",
    "AI services", "AI API", "AI consulting", "AI training", "AI education",
    "AI courses", "AI skills", "AI talent", "AI jobs", "AI careers", "AI community",
    "AI conference", "AI event", "AI news", "AI resources", "AI guides",
    "AI tutorials", "AI for startups", "AI for enterprises", "AI for SMEs",
    "AI for non-profits", "AI for government", "AI for healthcare", "AI for finance",
    "AI for education", "AI for retail", "AI for manufacturing", "AI for agriculture",
    "AI for transportation", "AI for gaming", "AI for entertainment", "AI for media",
    "AI for security", "AI for sustainability", "AI for environmental protection",
    "AI for climate change", "AI for social good", "AI in the metaverse",
    "AI and blockchain", "AI and IoT (Internet of Things)", "AI and robotics",
    "AI and cybersecurity", "AI and data privacy", "AI and GDPR", "AI compliance",
    "AI standards", "AI regulations", "AI assistant app", "Personal AI assistant",
    "Virtual assistant AI", "AI chatbot", "AI bot", "Intelligent chatbot",
    "Conversational AI", "Smart assistant", "AI helper", "Digital assistant",
    "AI support", "AI assistance", "AI concierge", "AI personal assistant",
    "AI for tasks", "AI task management", "AI scheduling", "AI reminders",
    "AI notifications", "AI communication", "AI productivity", "AI efficiency",
    "AI workflow", "AI automation tools", "AI powered productivity tools",
    "AI personal manager", "AI digital secretary", "AI task automation",
    "AI meeting assistant", "AI email assistant", "AI content assistant",
    "AI writing assistant", "AI summarization", "AI transcription",
    "AI note taking", "AI data entry", "AI research assistant",
    "AI presentation creation", "AI project management", "AI calendar management",
    "AI travel planning", "AI shopping assistant", "AI financial planning",
    "AI health monitoring", "AI customer support", "AI customer service",
    "AI feedback", "AI surveys", "AI data analysis", "AI reporting",
    "AI decision making", "AI problem solving", "AI innovation partner",
    "AI learning assistant", "AI language learning", "AI translation",
    "AI for students", "AI for teachers", "AI for professionals",
    "AI for remote work", "AI for collaboration", "AI team assistant",
    "AI for startups", "AI for small businesses", "AI for solopreneurs",
    "AI for creatives", "AI for researchers", "AI for educators",
    "AI for managers", "AI for executives", "AI for developers",
    "AI for designers", "AI art generator", "AI image generator", "AI artwork",
    "AI generated art", "AI painting", "AI illustration", "AI digital art",
    "AI creative tools", "AI art creation", "AI visual art", "Generative AI art",
    "Text to image AI", "Image to image AI", "AI art styles", "AI art techniques",
    "AI art effects", "AI art filters", "AI art editing", "AI art enhancement",
    "AI art customization", "AI art collaboration", "AI art platform",
    "AI art community", "AI art marketplace", "AI art for sale",
    "AI art for galleries", "AI art for personal use", "AI art for commercial use",
    "AI art trends", "AI art history", "AI artistic expression", "AI creativity",
    "AI design tools", "AI visual design", "AI graphic design", "AI logo design",
    "AI poster design", "AI banner design", "AI character design",
    "AI concept art", "AI game art", "AI animation", "AI video art",
    "AI art tutorials", "AI art resources", "AI art for beginners",
    "AI art for professionals", "AI for visual artists", "AI for designers",
    "AI for illustrators", "AI for animators", "AI art tools online",
    "Best AI art generator", "Free AI art generator", "AI art software",
    "AI art apps", "AI image synthesis", "AI drawing tool", "AI sketching tool",
    "AI image analysis", "AI image recognition", "AI object detection",
    "AI facial recognition", "AI image processing", "AI computer vision",
    "AI visual analysis", "AI image classification", "AI image segmentation",
    "AI image understanding", "AI scene understanding", "AI image comparison",
    "AI image search", "AI image annotation", "AI image tagging",
    "AI image metadata", "AI image forensics", "AI image enhancement",
    "AI image restoration", "AI image transformation", "AI image manipulation",
    "AI image editing tools", "AI video analysis", "AI video recognition",
    "AI video object tracking", "AI visual data", "AI for visual tasks",
    "AI in imaging", "AI for pattern recognition", "AI for anomaly detection",
    "AI medical image analysis", "AI satellite image analysis",
    "AI drone image analysis", "AI security camera analysis", "AI surveillance",
    "AI industrial inspection", "AI quality control", "AI for content moderation",
    "AI for e-commerce", "AI for marketing", "AI for retail", "AI for logistics",
    "AI for agriculture", "AI for environmental monitoring",
    "AI for scientific research", "AI for traffic management",
    "AI for autonomous vehicles", "AI for robots", "AI in manufacturing",
    "AI in healthcare", "AI in finance", "AI in education", "AI visual intelligence",
    "AI for visual search", "AI image similarity", "AI search engine",
    "Intelligent search", "AI powered search", "Smart search engine",
    "AI information retrieval", "AI knowledge graph", "AI semantic search",
    "AI contextual search", "AI natural language search", "AI question answering",
    "AI query understanding", "AI search optimization", "AI search algorithms",
    "AI search ranking", "AI search results", "AI search experience",
    "AI search interface", "AI search personalization", "AI search customization",
    "AI search recommendations", "AI search trends", "AI search analytics",
    "AI search for research", "AI search for data analysis",
    "AI search for business intelligence", "AI search for market research",
    "AI search for competitive intelligence", "AI search for patent research",
    "AI search for legal research", "AI search for academic research",
    "AI search for scientific research", "AI search for content discovery",
    "AI search for news", "AI search for articles", "AI search for websites",
    "AI search for images", "AI search for videos", "AI search for documents",
    "AI search for audio", "AI search for knowledge", "AI search for answers",
    "AI search for insights", "AI search for understanding", "AI search tool",
    "AI search platform", "AI search solution", "Best AI search engine",
    "Fast AI search", "Accurate AI search", "Comprehensive AI search",
    "Advanced AI search", "AI search integration", "AI search API",
    "AI search services", "AI for information management",
    "how to use ai for creative art",
    "ai tools for enhancing images online",
    "best ai search engine for scientific papers",
    "ai assistant for small business productivity",
    "ai powered personal assistant for remote work",
    "ai art generator with text prompts",
    "ai image analysis for object identification",
    "intelligent search engine with contextual understanding",
    "AI chatbot for customer support and inquiries",
    "how to use AI to increase productivity",
    "use AI to make art",
    "use AI to find information quickly",
    "use AI to help manage tasks",
    "improve workflow with AI",
    "increase work efficiency with AI",
    "discover AI tools for businesses"
  ],
  authors: [{ name: "Ahmed Helmy Eletr" }],
  creator: "AhmedHelmyDev",
  publisher: "MindBot Ai",
  openGraph: {
    title: "MindBot Ai: Into The MindVerse",
    description:
      "Experience the future of AI with MindBot-1.5-Pro. Featuring cutting-edge capabilities in art creation, image analysis, and smart search. Dive into a world of intelligent assistance.",
    url: "https://mindbotai.netlify.app",
    siteName: "MindBot Ai",
    images: [
      {
        url: "https://i.ibb.co/Hp4s6Jg/Untitled.jpg",
        width: 1200,
        height: 630,
        alt: "MindBot AI Banner",
      },
    ],
    locale: "en_EG",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MindBot AI: Revolutionizing AI Assistance",
    description: "MindBot: The next generation of AI assistants is here. Explore creative AI tools, intelligent image analysis, and smart search technology, all powered by our advanced AI.",
    creator: "@MindBotAI",
    images: ["https://i.ibb.co/Hp4s6Jg/Untitled.jpg"],
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${OutfitFont.className} dark:bg-[#131314] h-dvh w-full overflow-hidden bg-white text-black dark:text-white`}
      >
        <ThemeProviders>
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
